### ISSUE TITLE
How did you decide to use Profunctor Optics?

### ISSUE THREAD

**Issue by rain-1** [Mojang/DataFixerUpper#21]
Hello, thanks for the code release!

I found it fascinating that this library is using such advanced technology from the category theory/functional programming world!

Could you tell us a bit about how you learned about these tools and how you decided to use them in practice?

All the best

**Comment by RainWarrior** [comment]
Needed something to represent "access and modify this part of the big object deep inside", learned about optics as a natural representation of that; profunctor optics were easier to understand/implement than classic ones for me personally
