### ISSUE TITLE
Documentation Comments

### ISSUE THREAD

**Issue by kvverti** [Mojang/DataFixerUpper#47]
There are very few documentation comments, and the ones that are there are not very useful. Did you all strip the comments from the repository before publishing DFU?

**Comment by liach** [comment]
> Did you all strip the comments from the repository before publishing DFU?

I don't think so. https://github.com/Mojang/DataFixerUpper/pull/48/files#diff-1e787bae83ebfd257b197c59e8a71eb6R27

**Comment by RainWarrior** [comment]
No, this is all there ever was; naming of things follows the naming in linked papers, there's not much extra that was done, and where things do not follow directly there are comments
