### ISSUE TITLE
draw 2d floor plan

### ISSUE THREAD

**Issue by amazed007** [Mojang/DataFixerUpper#75]
[](https://www.fiverr.com/mdmazed583/draw-redraw-architectural-2d-floor-plan-autocad-2d-drawings-and-2d-floor-plans)

**Comment by amazed007** [comment]
https://www.fiverr.com/mdmazed583/draw-redraw-architectural-2d-floor-plan-autocad-2d-drawings-and-2d-floor-plans

**Comment by MiniDigger** [comment]
put your spam elsewhere please
